### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by aduckworth** [trevordevore/screensteps-cl-exporter#19]
I get the following error when running the script.

Traceback (most recent call last):
  File "ss_exporter.py", line 4, in <module>
    import requests
ImportError: No module named requests

**Comment by trevordevore** [comment]
@aduckworth You are missing the `requests` module. You can install that using [`pip`](https://pypi.python.org/pypi/pip) or just download the compiled version: http://help.screensteps.com/m/screensteps-api/l/740641-python-command-line-exporter

**Comment by aduckworth** [comment]
@trevordevore Thanks for the information! I downloaded and ran the compiled version, but received the following error:

SyntaxError: Non-ASCII character '\xcf' in file ss_exporter on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Could it be I am running the wrong version of python? I am on 2.7.10.

**Comment by trevordevore** [comment]
I tracked this down today. On macOS the encoding for stdout was not being set correctly when running as a compiled application which triggered an error if a site, manual, chapter, or article had unicode characters in the title. Running the script itself with python would work fine.The script has been updated and a new macOS executable has been uploaded.
